# Random seed for reproducibility
random_seed: 42

# Data configuration
data:
  train_split: 0.8
  val_split: 0.2
  have_test: false
  shuffle: true

# Model architecture
model:
  hidden_dims: [64, 32]  # Even smaller network
  bottleneck_dim: 16
  activation: 'modrelu'

# Training configuration
training:
  batch_size: 16  # Smaller batch size
  max_epochs: 50  # Fewer epochs to start
  learning_rate: 0.001  # Higher learning rate
  weight_decay: 0.0
  early_stopping_patience: 5
  log_every_n_steps: 1  # More frequent logging

# Directories and files
paths:
  checkpoint_dir: checkpoints
  log_dir: logs
  data_dir: data
  data_file: data.npy  # Your data file name 