# Random seed for reproducibility
random_seed: 42

# Data configuration
data:
  train_split: 0.8
  val_split: 0.2
  have_test: false
  shuffle: true

# Model architecture
model:
  hidden_dims: [256, 128, 64]  # Increased network capacity
  bottleneck_dim: 32  # Increased bottleneck dimension
  activation: 'modrelu'

# Training configuration
training:
  batch_size: 64
  max_epochs: 300  # Increased epochs
  learning_rate: 0.0001  # Reduced learning rate
  weight_decay: 0.00001  # Reduced weight decay
  early_stopping_patience: 20  # Increased patience
  log_every_n_steps: 10

# Directories and files
paths:
  checkpoint_dir: checkpoints
  log_dir: logs
  data_dir: data
  data_file: data.npy  # Your data file name 