# Random seed for reproducibility
random_seed: 42

# Data configuration
data:
  train_split: 0.8
  val_split: 0.2
  have_test: false
  shuffle: true

# Model architecture
model:
  hidden_dims: [256, 128, 64]  # Hidden layer dimensions
  bottleneck_dim: 32           # Bottleneck dimension
  activation: modrelu          # Activation function

# Training configuration
training:
  batch_size: 32              # Reduced batch size
  max_epochs: 200             # Max epochs
  learning_rate: 0.0005       # Adjusted learning rate
  weight_decay: 0.00001       # Reduced weight decay
  early_stopping_patience: 20  # Early stopping patience
  log_every_n_steps: 10

# Directories and files
paths:
  checkpoint_dir: checkpoints
  log_dir: logs
  data_dir: data
  data_file: data.npy  # Your data file name 