# Random seed for reproducibility
random_seed: 42

# Data configuration
data:
  train_split: 0.8
  val_split: 0.2
  have_test: false
  shuffle: true

# Model architecture
model:
  hidden_dims: [256, 128, 64]  # Increased network capacity
  bottleneck_dim: 32  # Increased bottleneck dimension
  activation: 'modrelu'

# Training configuration
training:
  batch_size: 32
  max_epochs: 300  # Increased max epochs
  learning_rate: 0.01
  weight_decay: 1e-5
  early_stopping_patience: 30  # Increased patience
  early_stopping_min_delta: 1e-5  # Added minimum change threshold
  log_every_n_steps: 1

# Directories and files
paths:
  checkpoint_dir: checkpoints
  log_dir: logs
  data_dir: data
  data_file: data.npy  # Your data file name 