# Random seed for reproducibility
random_seed: 42

# Data configuration
data:
  train_split: 0.8
  val_split: 0.2
  have_test: false
  shuffle: true

# Model architecture
model:
  hidden_dims: [128, 64, 32]  # Reduced network size for stability
  bottleneck_dim: 16  # Reduced bottleneck dimension
  activation: 'modrelu'

# Training configuration
training:
  batch_size: 32  # Smaller batch size for stability
  max_epochs: 100
  learning_rate: 0.0005  # Increased learning rate
  weight_decay: 0.0  # Removed weight decay for now
  early_stopping_patience: 10
  log_every_n_steps: 10

# Directories and files
paths:
  checkpoint_dir: checkpoints
  log_dir: logs
  data_dir: data
  data_file: data.npy  # Your data file name 